# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Main branch build

on:
  push: 
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      - name: Install yarn
        run: corepack enable
      - name: Set yarn version to latest stable
        run: corepack prepare yarn@stable --activate
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
      - name: Replace Action
        uses: datamonsters/replace-action@v2
        with:
          files: ./.yarnrc.yml
          replacements: NPM_TOKEN=${{secrets.npm_token}}
      - name: Publish beta version to NPM (uses package.json version)
        run: yarn npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      

      
  
