# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      - name: Install yarn
        run: corepack enable
      - name: Set yarn version to latest stable
        run: corepack prepare yarn@stable --activate
      - name: Install dependencies
        run: yarn install
      - name: install semantic-release extra plugins
        run: yarn add -D @semantic-release/changelog @semantic-release/git @semantic-release/github semantic-release-yarn
      - name: lint
        run: yarn lint
      - name: Build
        run: yarn build
      # - name: Replace Action
      #   uses: datamonsters/replace-action@v2
      #   with:
      #     files: ./.yarnrc.yml
      #     replacements: NPM_TOKEN=${{secrets.npm_token}}
      - name: Release
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          YARN_NPM_PUBLISH_REGISTRY: https://registry.npmjs.org
        run: npx semantic-release
      # - name: Publish beta version to NPM (uses package.json version)
      #   run: yarn npm publish --tag stable --access public
